// Generated by gencpp from file micro_doppler_pkg/MicroDoppler_m.msg
// DO NOT EDIT!


#ifndef MICRO_DOPPLER_PKG_MESSAGE_MICRODOPPLER_M_H
#define MICRO_DOPPLER_PKG_MESSAGE_MICRODOPPLER_M_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace micro_doppler_pkg
{
template <class ContainerAllocator>
struct MicroDoppler_m_
{
  typedef MicroDoppler_m_<ContainerAllocator> Type;

  MicroDoppler_m_()
    : header()
    , time_domain_bins(0)
    , num_chirps(0)
    , target_idx(0)
    , micro_doppler_array()
    , posX(0.0)
    , posY(0.0)
    , velX(0.0)
    , velY(0.0)  {
    }
  MicroDoppler_m_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , time_domain_bins(0)
    , num_chirps(0)
    , target_idx(0)
    , micro_doppler_array(_alloc)
    , posX(0.0)
    , posY(0.0)
    , velX(0.0)
    , velY(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint16_t _time_domain_bins_type;
  _time_domain_bins_type time_domain_bins;

   typedef uint16_t _num_chirps_type;
  _num_chirps_type num_chirps;

   typedef uint8_t _target_idx_type;
  _target_idx_type target_idx;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _micro_doppler_array_type;
  _micro_doppler_array_type micro_doppler_array;

   typedef float _posX_type;
  _posX_type posX;

   typedef float _posY_type;
  _posY_type posY;

   typedef float _velX_type;
  _velX_type velX;

   typedef float _velY_type;
  _velY_type velY;





  typedef boost::shared_ptr< ::micro_doppler_pkg::MicroDoppler_m_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::micro_doppler_pkg::MicroDoppler_m_<ContainerAllocator> const> ConstPtr;

}; // struct MicroDoppler_m_

typedef ::micro_doppler_pkg::MicroDoppler_m_<std::allocator<void> > MicroDoppler_m;

typedef boost::shared_ptr< ::micro_doppler_pkg::MicroDoppler_m > MicroDoppler_mPtr;
typedef boost::shared_ptr< ::micro_doppler_pkg::MicroDoppler_m const> MicroDoppler_mConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::micro_doppler_pkg::MicroDoppler_m_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::micro_doppler_pkg::MicroDoppler_m_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace micro_doppler_pkg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'micro_doppler_pkg': ['/home/ece561/Projects/ti_ros/src/micro_doppler_pkg/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::micro_doppler_pkg::MicroDoppler_m_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::micro_doppler_pkg::MicroDoppler_m_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::micro_doppler_pkg::MicroDoppler_m_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::micro_doppler_pkg::MicroDoppler_m_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::micro_doppler_pkg::MicroDoppler_m_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::micro_doppler_pkg::MicroDoppler_m_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::micro_doppler_pkg::MicroDoppler_m_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f18c4823afa7776d20d07fa149c4e3d2";
  }

  static const char* value(const ::micro_doppler_pkg::MicroDoppler_m_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf18c4823afa7776dULL;
  static const uint64_t static_value2 = 0x20d07fa149c4e3d2ULL;
};

template<class ContainerAllocator>
struct DataType< ::micro_doppler_pkg::MicroDoppler_m_<ContainerAllocator> >
{
  static const char* value()
  {
    return "micro_doppler_pkg/MicroDoppler_m";
  }

  static const char* value(const ::micro_doppler_pkg::MicroDoppler_m_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::micro_doppler_pkg::MicroDoppler_m_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
uint16 time_domain_bins\n\
uint16 num_chirps\n\
uint8 target_idx\n\
float32[] micro_doppler_array\n\
float32 posX\n\
float32 posY\n\
float32 velX\n\
float32 velY\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::micro_doppler_pkg::MicroDoppler_m_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::micro_doppler_pkg::MicroDoppler_m_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.time_domain_bins);
      stream.next(m.num_chirps);
      stream.next(m.target_idx);
      stream.next(m.micro_doppler_array);
      stream.next(m.posX);
      stream.next(m.posY);
      stream.next(m.velX);
      stream.next(m.velY);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MicroDoppler_m_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::micro_doppler_pkg::MicroDoppler_m_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::micro_doppler_pkg::MicroDoppler_m_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "time_domain_bins: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.time_domain_bins);
    s << indent << "num_chirps: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.num_chirps);
    s << indent << "target_idx: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.target_idx);
    s << indent << "micro_doppler_array[]" << std::endl;
    for (size_t i = 0; i < v.micro_doppler_array.size(); ++i)
    {
      s << indent << "  micro_doppler_array[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.micro_doppler_array[i]);
    }
    s << indent << "posX: ";
    Printer<float>::stream(s, indent + "  ", v.posX);
    s << indent << "posY: ";
    Printer<float>::stream(s, indent + "  ", v.posY);
    s << indent << "velX: ";
    Printer<float>::stream(s, indent + "  ", v.velX);
    s << indent << "velY: ";
    Printer<float>::stream(s, indent + "  ", v.velY);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MICRO_DOPPLER_PKG_MESSAGE_MICRODOPPLER_M_H
