(cl:in-package ti_mmwave_rospkg-msg)
(cl:export '(HEADER-VAL
          HEADER
          POINT_ID-VAL
          POINT_ID
          TARGET_IDX-VAL
          TARGET_IDX
          X-VAL
          X
          Y-VAL
          Y
          Z-VAL
          Z
          RANGE-VAL
          RANGE
          VELOCITY-VAL
          VELOCITY
          DOPPLER_BIN-VAL
          DOPPLER_BIN
          BEARING-VAL
          BEARING
          INTENSITY-VAL
          INTENSITY
          POSX-VAL
          POSX
          POSY-VAL
          POSY
          VELX-VAL
          VELX
          VELY-VAL
          VELY
))